// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mars_rover.proto
// Protobuf C++ Version: 5.28.3

#include "mars_rover.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace marsrover {

inline constexpr WheelLEDRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : wheel_number_{0},
        on_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WheelLEDRequest::WheelLEDRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WheelLEDRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WheelLEDRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WheelLEDRequestDefaultTypeInternal() {}
  union {
    WheelLEDRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WheelLEDRequestDefaultTypeInternal _WheelLEDRequest_default_instance_;

inline constexpr UltrasoundResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : distance_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UltrasoundResponse::UltrasoundResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UltrasoundResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UltrasoundResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UltrasoundResponseDefaultTypeInternal() {}
  union {
    UltrasoundResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UltrasoundResponseDefaultTypeInternal _UltrasoundResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR UltrasoundRequest::UltrasoundRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UltrasoundRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UltrasoundRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UltrasoundRequestDefaultTypeInternal() {}
  union {
    UltrasoundRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UltrasoundRequestDefaultTypeInternal _UltrasoundRequest_default_instance_;

inline constexpr TurnRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : angle_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TurnRequest::TurnRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TurnRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TurnRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TurnRequestDefaultTypeInternal() {}
  union {
    TurnRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TurnRequestDefaultTypeInternal _TurnRequest_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR StopRequest::StopRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct StopRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StopRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StopRequestDefaultTypeInternal() {}
  union {
    StopRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StopRequestDefaultTypeInternal _StopRequest_default_instance_;

inline constexpr RotateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : angle_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RotateRequest::RotateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RotateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RotateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RotateRequestDefaultTypeInternal() {}
  union {
    RotateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RotateRequestDefaultTypeInternal _RotateRequest_default_instance_;

inline constexpr LEDRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : on_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LEDRequest::LEDRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LEDRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LEDRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LEDRequestDefaultTypeInternal() {}
  union {
    LEDRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LEDRequestDefaultTypeInternal _LEDRequest_default_instance_;

inline constexpr DriveRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : speed_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DriveRequest::DriveRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DriveRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DriveRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DriveRequestDefaultTypeInternal() {}
  union {
    DriveRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DriveRequestDefaultTypeInternal _DriveRequest_default_instance_;

inline constexpr CommandResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CommandResponse::CommandResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CommandResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandResponseDefaultTypeInternal() {}
  union {
    CommandResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandResponseDefaultTypeInternal _CommandResponse_default_instance_;

inline constexpr CameraStreamResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : stream_url_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CameraStreamResponse::CameraStreamResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CameraStreamResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraStreamResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraStreamResponseDefaultTypeInternal() {}
  union {
    CameraStreamResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraStreamResponseDefaultTypeInternal _CameraStreamResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR CameraStreamRequest::CameraStreamRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CameraStreamRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraStreamRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraStreamRequestDefaultTypeInternal() {}
  union {
    CameraStreamRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraStreamRequestDefaultTypeInternal _CameraStreamRequest_default_instance_;
}  // namespace marsrover
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mars_5frover_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mars_5frover_2eproto = nullptr;
const ::uint32_t
    TableStruct_mars_5frover_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::DriveRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::DriveRequest, _impl_.speed_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::StopRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::TurnRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::TurnRequest, _impl_.angle_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::RotateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::RotateRequest, _impl_.angle_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::CommandResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::CommandResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::marsrover::CommandResponse, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::LEDRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::LEDRequest, _impl_.on_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::WheelLEDRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::WheelLEDRequest, _impl_.wheel_number_),
        PROTOBUF_FIELD_OFFSET(::marsrover::WheelLEDRequest, _impl_.on_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::UltrasoundRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::UltrasoundResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::UltrasoundResponse, _impl_.distance_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::CameraStreamRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::marsrover::CameraStreamResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::marsrover::CameraStreamResponse, _impl_.stream_url_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::marsrover::DriveRequest)},
        {9, -1, -1, sizeof(::marsrover::StopRequest)},
        {17, -1, -1, sizeof(::marsrover::TurnRequest)},
        {26, -1, -1, sizeof(::marsrover::RotateRequest)},
        {35, -1, -1, sizeof(::marsrover::CommandResponse)},
        {45, -1, -1, sizeof(::marsrover::LEDRequest)},
        {54, -1, -1, sizeof(::marsrover::WheelLEDRequest)},
        {64, -1, -1, sizeof(::marsrover::UltrasoundRequest)},
        {72, -1, -1, sizeof(::marsrover::UltrasoundResponse)},
        {81, -1, -1, sizeof(::marsrover::CameraStreamRequest)},
        {89, -1, -1, sizeof(::marsrover::CameraStreamResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::marsrover::_DriveRequest_default_instance_._instance,
    &::marsrover::_StopRequest_default_instance_._instance,
    &::marsrover::_TurnRequest_default_instance_._instance,
    &::marsrover::_RotateRequest_default_instance_._instance,
    &::marsrover::_CommandResponse_default_instance_._instance,
    &::marsrover::_LEDRequest_default_instance_._instance,
    &::marsrover::_WheelLEDRequest_default_instance_._instance,
    &::marsrover::_UltrasoundRequest_default_instance_._instance,
    &::marsrover::_UltrasoundResponse_default_instance_._instance,
    &::marsrover::_CameraStreamRequest_default_instance_._instance,
    &::marsrover::_CameraStreamResponse_default_instance_._instance,
};
const char descriptor_table_protodef_mars_5frover_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020mars_rover.proto\022\tmarsrover\"\035\n\014DriveRe"
    "quest\022\r\n\005speed\030\001 \001(\002\"\r\n\013StopRequest\"\034\n\013T"
    "urnRequest\022\r\n\005angle\030\001 \001(\002\"\036\n\rRotateReque"
    "st\022\r\n\005angle\030\001 \001(\002\"3\n\017CommandResponse\022\017\n\007"
    "success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\030\n\nLEDReq"
    "uest\022\n\n\002on\030\001 \001(\010\"3\n\017WheelLEDRequest\022\024\n\014w"
    "heel_number\030\001 \001(\005\022\n\n\002on\030\002 \001(\010\"\023\n\021Ultraso"
    "undRequest\"&\n\022UltrasoundResponse\022\020\n\010dist"
    "ance\030\001 \001(\002\"\025\n\023CameraStreamRequest\"*\n\024Cam"
    "eraStreamResponse\022\022\n\nstream_url\030\001 \001(\t2\340\005"
    "\n\014RoverService\022C\n\014DriveForward\022\027.marsrov"
    "er.DriveRequest\032\032.marsrover.CommandRespo"
    "nse\022>\n\007Reverse\022\027.marsrover.DriveRequest\032"
    "\032.marsrover.CommandResponse\022>\n\010TurnLeft\022"
    "\026.marsrover.TurnRequest\032\032.marsrover.Comm"
    "andResponse\022\?\n\tTurnRight\022\026.marsrover.Tur"
    "nRequest\032\032.marsrover.CommandResponse\022@\n\n"
    "TurnOnSpot\022\026.marsrover.TurnRequest\032\032.mar"
    "srover.CommandResponse\022G\n\017RotatePeriscop"
    "e\022\030.marsrover.RotateRequest\032\032.marsrover."
    "CommandResponse\022F\n\021ControlHeadlights\022\025.m"
    "arsrover.LEDRequest\032\032.marsrover.CommandR"
    "esponse\022J\n\020ControlWheelLEDs\022\032.marsrover."
    "WheelLEDRequest\032\032.marsrover.CommandRespo"
    "nse\022W\n\030GetUltrasoundMeasurement\022\034.marsro"
    "ver.UltrasoundRequest\032\035.marsrover.Ultras"
    "oundResponse\022R\n\017GetCameraStream\022\036.marsro"
    "ver.CameraStreamRequest\032\037.marsrover.Came"
    "raStreamResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_mars_5frover_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mars_5frover_2eproto = {
    false,
    false,
    1144,
    descriptor_table_protodef_mars_5frover_2eproto,
    "mars_rover.proto",
    &descriptor_table_mars_5frover_2eproto_once,
    nullptr,
    0,
    11,
    schemas,
    file_default_instances,
    TableStruct_mars_5frover_2eproto::offsets,
    file_level_enum_descriptors_mars_5frover_2eproto,
    file_level_service_descriptors_mars_5frover_2eproto,
};
namespace marsrover {
// ===================================================================

class DriveRequest::_Internal {
 public:
};

DriveRequest::DriveRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.DriveRequest)
}
DriveRequest::DriveRequest(
    ::google::protobuf::Arena* arena, const DriveRequest& from)
    : DriveRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DriveRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DriveRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.speed_ = {};
}
DriveRequest::~DriveRequest() {
  // @@protoc_insertion_point(destructor:marsrover.DriveRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DriveRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    DriveRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_DriveRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &DriveRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<DriveRequest>(),
            ::google::protobuf::Message::GetNewImpl<DriveRequest>(),
            ::google::protobuf::Message::GetClearImpl<DriveRequest>(), &DriveRequest::ByteSizeLong,
                &DriveRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(DriveRequest, _impl_._cached_size_),
            false,
        },
        &DriveRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* DriveRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DriveRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::DriveRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float speed = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(DriveRequest, _impl_.speed_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float speed = 1;
    {PROTOBUF_FIELD_OFFSET(DriveRequest, _impl_.speed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DriveRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.DriveRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.speed_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DriveRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DriveRequest& this_ = static_cast<const DriveRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DriveRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DriveRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.DriveRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float speed = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_speed()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_speed(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.DriveRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DriveRequest::ByteSizeLong(const MessageLite& base) {
          const DriveRequest& this_ = static_cast<const DriveRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DriveRequest::ByteSizeLong() const {
          const DriveRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.DriveRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // float speed = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_speed()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DriveRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DriveRequest*>(&to_msg);
  auto& from = static_cast<const DriveRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.DriveRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_speed()) != 0) {
    _this->_impl_.speed_ = from._impl_.speed_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DriveRequest::CopyFrom(const DriveRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.DriveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DriveRequest::InternalSwap(DriveRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.speed_, other->_impl_.speed_);
}

::google::protobuf::Metadata DriveRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StopRequest::_Internal {
 public:
};

StopRequest::StopRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:marsrover.StopRequest)
}
StopRequest::StopRequest(
    ::google::protobuf::Arena* arena,
    const StopRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StopRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:marsrover.StopRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    StopRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_StopRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &StopRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<StopRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<StopRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<StopRequest>(), &StopRequest::ByteSizeLong,
                &StopRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(StopRequest, _impl_._cached_size_),
            false,
        },
        &StopRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* StopRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> StopRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::StopRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata StopRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TurnRequest::_Internal {
 public:
};

TurnRequest::TurnRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.TurnRequest)
}
TurnRequest::TurnRequest(
    ::google::protobuf::Arena* arena, const TurnRequest& from)
    : TurnRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE TurnRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TurnRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.angle_ = {};
}
TurnRequest::~TurnRequest() {
  // @@protoc_insertion_point(destructor:marsrover.TurnRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TurnRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    TurnRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_TurnRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &TurnRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<TurnRequest>(),
            ::google::protobuf::Message::GetNewImpl<TurnRequest>(),
            ::google::protobuf::Message::GetClearImpl<TurnRequest>(), &TurnRequest::ByteSizeLong,
                &TurnRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(TurnRequest, _impl_._cached_size_),
            false,
        },
        &TurnRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* TurnRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> TurnRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::TurnRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float angle = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(TurnRequest, _impl_.angle_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float angle = 1;
    {PROTOBUF_FIELD_OFFSET(TurnRequest, _impl_.angle_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void TurnRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.TurnRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.angle_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TurnRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TurnRequest& this_ = static_cast<const TurnRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TurnRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TurnRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.TurnRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float angle = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_angle()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_angle(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.TurnRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TurnRequest::ByteSizeLong(const MessageLite& base) {
          const TurnRequest& this_ = static_cast<const TurnRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TurnRequest::ByteSizeLong() const {
          const TurnRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.TurnRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // float angle = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_angle()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TurnRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TurnRequest*>(&to_msg);
  auto& from = static_cast<const TurnRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.TurnRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_angle()) != 0) {
    _this->_impl_.angle_ = from._impl_.angle_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TurnRequest::CopyFrom(const TurnRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.TurnRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TurnRequest::InternalSwap(TurnRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.angle_, other->_impl_.angle_);
}

::google::protobuf::Metadata TurnRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RotateRequest::_Internal {
 public:
};

RotateRequest::RotateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.RotateRequest)
}
RotateRequest::RotateRequest(
    ::google::protobuf::Arena* arena, const RotateRequest& from)
    : RotateRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RotateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RotateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.angle_ = {};
}
RotateRequest::~RotateRequest() {
  // @@protoc_insertion_point(destructor:marsrover.RotateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RotateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    RotateRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_RotateRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &RotateRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<RotateRequest>(),
            ::google::protobuf::Message::GetNewImpl<RotateRequest>(),
            ::google::protobuf::Message::GetClearImpl<RotateRequest>(), &RotateRequest::ByteSizeLong,
                &RotateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(RotateRequest, _impl_._cached_size_),
            false,
        },
        &RotateRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* RotateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RotateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::RotateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float angle = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(RotateRequest, _impl_.angle_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float angle = 1;
    {PROTOBUF_FIELD_OFFSET(RotateRequest, _impl_.angle_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RotateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.RotateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.angle_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RotateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RotateRequest& this_ = static_cast<const RotateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RotateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RotateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.RotateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float angle = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_angle()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_angle(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.RotateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RotateRequest::ByteSizeLong(const MessageLite& base) {
          const RotateRequest& this_ = static_cast<const RotateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RotateRequest::ByteSizeLong() const {
          const RotateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.RotateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // float angle = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_angle()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RotateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RotateRequest*>(&to_msg);
  auto& from = static_cast<const RotateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.RotateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_angle()) != 0) {
    _this->_impl_.angle_ = from._impl_.angle_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RotateRequest::CopyFrom(const RotateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.RotateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RotateRequest::InternalSwap(RotateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.angle_, other->_impl_.angle_);
}

::google::protobuf::Metadata RotateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CommandResponse::_Internal {
 public:
};

CommandResponse::CommandResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.CommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE CommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marsrover::CommandResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CommandResponse::CommandResponse(
    ::google::protobuf::Arena* arena,
    const CommandResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CommandResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:marsrover.CommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE CommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CommandResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
CommandResponse::~CommandResponse() {
  // @@protoc_insertion_point(destructor:marsrover.CommandResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CommandResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    CommandResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_CommandResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &CommandResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<CommandResponse>(),
            ::google::protobuf::Message::GetNewImpl<CommandResponse>(),
            ::google::protobuf::Message::GetClearImpl<CommandResponse>(), &CommandResponse::ByteSizeLong,
                &CommandResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(CommandResponse, _impl_._cached_size_),
            false,
        },
        &CommandResponse::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* CommandResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> CommandResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::CommandResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CommandResponse, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CommandResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommandResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(CommandResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(CommandResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\7\0\0\0\0\0"
    "marsrover.CommandResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void CommandResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.CommandResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CommandResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CommandResponse& this_ = static_cast<const CommandResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CommandResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CommandResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.CommandResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marsrover.CommandResponse.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.CommandResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CommandResponse::ByteSizeLong(const MessageLite& base) {
          const CommandResponse& this_ = static_cast<const CommandResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CommandResponse::ByteSizeLong() const {
          const CommandResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.CommandResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CommandResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CommandResponse*>(&to_msg);
  auto& from = static_cast<const CommandResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.CommandResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandResponse::CopyFrom(const CommandResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.CommandResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommandResponse::InternalSwap(CommandResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata CommandResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LEDRequest::_Internal {
 public:
};

LEDRequest::LEDRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.LEDRequest)
}
LEDRequest::LEDRequest(
    ::google::protobuf::Arena* arena, const LEDRequest& from)
    : LEDRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LEDRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LEDRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.on_ = {};
}
LEDRequest::~LEDRequest() {
  // @@protoc_insertion_point(destructor:marsrover.LEDRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LEDRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    LEDRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_LEDRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &LEDRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<LEDRequest>(),
            ::google::protobuf::Message::GetNewImpl<LEDRequest>(),
            ::google::protobuf::Message::GetClearImpl<LEDRequest>(), &LEDRequest::ByteSizeLong,
                &LEDRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_._cached_size_),
            false,
        },
        &LEDRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* LEDRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LEDRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::LEDRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool on = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LEDRequest, _impl_.on_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_.on_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool on = 1;
    {PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_.on_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void LEDRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.LEDRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.on_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LEDRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LEDRequest& this_ = static_cast<const LEDRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LEDRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LEDRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.LEDRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool on = 1;
          if (this_._internal_on() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_on(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.LEDRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LEDRequest::ByteSizeLong(const MessageLite& base) {
          const LEDRequest& this_ = static_cast<const LEDRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LEDRequest::ByteSizeLong() const {
          const LEDRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.LEDRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool on = 1;
            if (this_._internal_on() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LEDRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LEDRequest*>(&to_msg);
  auto& from = static_cast<const LEDRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.LEDRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_on() != 0) {
    _this->_impl_.on_ = from._impl_.on_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LEDRequest::CopyFrom(const LEDRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.LEDRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LEDRequest::InternalSwap(LEDRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.on_, other->_impl_.on_);
}

::google::protobuf::Metadata LEDRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WheelLEDRequest::_Internal {
 public:
};

WheelLEDRequest::WheelLEDRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.WheelLEDRequest)
}
WheelLEDRequest::WheelLEDRequest(
    ::google::protobuf::Arena* arena, const WheelLEDRequest& from)
    : WheelLEDRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE WheelLEDRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void WheelLEDRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, wheel_number_),
           0,
           offsetof(Impl_, on_) -
               offsetof(Impl_, wheel_number_) +
               sizeof(Impl_::on_));
}
WheelLEDRequest::~WheelLEDRequest() {
  // @@protoc_insertion_point(destructor:marsrover.WheelLEDRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void WheelLEDRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    WheelLEDRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_WheelLEDRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &WheelLEDRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<WheelLEDRequest>(),
            ::google::protobuf::Message::GetNewImpl<WheelLEDRequest>(),
            ::google::protobuf::Message::GetClearImpl<WheelLEDRequest>(), &WheelLEDRequest::ByteSizeLong,
                &WheelLEDRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_._cached_size_),
            false,
        },
        &WheelLEDRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* WheelLEDRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> WheelLEDRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::WheelLEDRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool on = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WheelLEDRequest, _impl_.on_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.on_)}},
    // int32 wheel_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WheelLEDRequest, _impl_.wheel_number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.wheel_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 wheel_number = 1;
    {PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.wheel_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool on = 2;
    {PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.on_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void WheelLEDRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.WheelLEDRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.wheel_number_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.on_) -
      reinterpret_cast<char*>(&_impl_.wheel_number_)) + sizeof(_impl_.on_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WheelLEDRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WheelLEDRequest& this_ = static_cast<const WheelLEDRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WheelLEDRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WheelLEDRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.WheelLEDRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 wheel_number = 1;
          if (this_._internal_wheel_number() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_wheel_number(), target);
          }

          // bool on = 2;
          if (this_._internal_on() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_on(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.WheelLEDRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WheelLEDRequest::ByteSizeLong(const MessageLite& base) {
          const WheelLEDRequest& this_ = static_cast<const WheelLEDRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WheelLEDRequest::ByteSizeLong() const {
          const WheelLEDRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.WheelLEDRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 wheel_number = 1;
            if (this_._internal_wheel_number() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_wheel_number());
            }
            // bool on = 2;
            if (this_._internal_on() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WheelLEDRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WheelLEDRequest*>(&to_msg);
  auto& from = static_cast<const WheelLEDRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.WheelLEDRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_wheel_number() != 0) {
    _this->_impl_.wheel_number_ = from._impl_.wheel_number_;
  }
  if (from._internal_on() != 0) {
    _this->_impl_.on_ = from._impl_.on_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WheelLEDRequest::CopyFrom(const WheelLEDRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.WheelLEDRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WheelLEDRequest::InternalSwap(WheelLEDRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.on_)
      + sizeof(WheelLEDRequest::_impl_.on_)
      - PROTOBUF_FIELD_OFFSET(WheelLEDRequest, _impl_.wheel_number_)>(
          reinterpret_cast<char*>(&_impl_.wheel_number_),
          reinterpret_cast<char*>(&other->_impl_.wheel_number_));
}

::google::protobuf::Metadata WheelLEDRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UltrasoundRequest::_Internal {
 public:
};

UltrasoundRequest::UltrasoundRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:marsrover.UltrasoundRequest)
}
UltrasoundRequest::UltrasoundRequest(
    ::google::protobuf::Arena* arena,
    const UltrasoundRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UltrasoundRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:marsrover.UltrasoundRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UltrasoundRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_UltrasoundRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UltrasoundRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<UltrasoundRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<UltrasoundRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<UltrasoundRequest>(), &UltrasoundRequest::ByteSizeLong,
                &UltrasoundRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UltrasoundRequest, _impl_._cached_size_),
            false,
        },
        &UltrasoundRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UltrasoundRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> UltrasoundRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::UltrasoundRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata UltrasoundRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UltrasoundResponse::_Internal {
 public:
};

UltrasoundResponse::UltrasoundResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.UltrasoundResponse)
}
UltrasoundResponse::UltrasoundResponse(
    ::google::protobuf::Arena* arena, const UltrasoundResponse& from)
    : UltrasoundResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UltrasoundResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UltrasoundResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.distance_ = {};
}
UltrasoundResponse::~UltrasoundResponse() {
  // @@protoc_insertion_point(destructor:marsrover.UltrasoundResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UltrasoundResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UltrasoundResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UltrasoundResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UltrasoundResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UltrasoundResponse>(),
            ::google::protobuf::Message::GetNewImpl<UltrasoundResponse>(),
            ::google::protobuf::Message::GetClearImpl<UltrasoundResponse>(), &UltrasoundResponse::ByteSizeLong,
                &UltrasoundResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UltrasoundResponse, _impl_._cached_size_),
            false,
        },
        &UltrasoundResponse::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UltrasoundResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> UltrasoundResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::UltrasoundResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float distance = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(UltrasoundResponse, _impl_.distance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float distance = 1;
    {PROTOBUF_FIELD_OFFSET(UltrasoundResponse, _impl_.distance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UltrasoundResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.UltrasoundResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.distance_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UltrasoundResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UltrasoundResponse& this_ = static_cast<const UltrasoundResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UltrasoundResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UltrasoundResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.UltrasoundResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float distance = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_distance()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_distance(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.UltrasoundResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UltrasoundResponse::ByteSizeLong(const MessageLite& base) {
          const UltrasoundResponse& this_ = static_cast<const UltrasoundResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UltrasoundResponse::ByteSizeLong() const {
          const UltrasoundResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.UltrasoundResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // float distance = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_distance()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UltrasoundResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UltrasoundResponse*>(&to_msg);
  auto& from = static_cast<const UltrasoundResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.UltrasoundResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_distance()) != 0) {
    _this->_impl_.distance_ = from._impl_.distance_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UltrasoundResponse::CopyFrom(const UltrasoundResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.UltrasoundResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UltrasoundResponse::InternalSwap(UltrasoundResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.distance_, other->_impl_.distance_);
}

::google::protobuf::Metadata UltrasoundResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraStreamRequest::_Internal {
 public:
};

CameraStreamRequest::CameraStreamRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:marsrover.CameraStreamRequest)
}
CameraStreamRequest::CameraStreamRequest(
    ::google::protobuf::Arena* arena,
    const CameraStreamRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraStreamRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:marsrover.CameraStreamRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    CameraStreamRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_CameraStreamRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &CameraStreamRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<CameraStreamRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CameraStreamRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CameraStreamRequest>(), &CameraStreamRequest::ByteSizeLong,
                &CameraStreamRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(CameraStreamRequest, _impl_._cached_size_),
            false,
        },
        &CameraStreamRequest::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* CameraStreamRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> CameraStreamRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::CameraStreamRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata CameraStreamRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraStreamResponse::_Internal {
 public:
};

CameraStreamResponse::CameraStreamResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:marsrover.CameraStreamResponse)
}
inline PROTOBUF_NDEBUG_INLINE CameraStreamResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::marsrover::CameraStreamResponse& from_msg)
      : stream_url_(arena, from.stream_url_),
        _cached_size_{0} {}

CameraStreamResponse::CameraStreamResponse(
    ::google::protobuf::Arena* arena,
    const CameraStreamResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CameraStreamResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:marsrover.CameraStreamResponse)
}
inline PROTOBUF_NDEBUG_INLINE CameraStreamResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : stream_url_(arena),
        _cached_size_{0} {}

inline void CameraStreamResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CameraStreamResponse::~CameraStreamResponse() {
  // @@protoc_insertion_point(destructor:marsrover.CameraStreamResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CameraStreamResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.stream_url_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    CameraStreamResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_CameraStreamResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &CameraStreamResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<CameraStreamResponse>(),
            ::google::protobuf::Message::GetNewImpl<CameraStreamResponse>(),
            ::google::protobuf::Message::GetClearImpl<CameraStreamResponse>(), &CameraStreamResponse::ByteSizeLong,
                &CameraStreamResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(CameraStreamResponse, _impl_._cached_size_),
            false,
        },
        &CameraStreamResponse::kDescriptorMethods,
        &descriptor_table_mars_5frover_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* CameraStreamResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 49, 2> CameraStreamResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::marsrover::CameraStreamResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string stream_url = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CameraStreamResponse, _impl_.stream_url_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string stream_url = 1;
    {PROTOBUF_FIELD_OFFSET(CameraStreamResponse, _impl_.stream_url_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\12\0\0\0\0\0\0"
    "marsrover.CameraStreamResponse"
    "stream_url"
  }},
};

PROTOBUF_NOINLINE void CameraStreamResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:marsrover.CameraStreamResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stream_url_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CameraStreamResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CameraStreamResponse& this_ = static_cast<const CameraStreamResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CameraStreamResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CameraStreamResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:marsrover.CameraStreamResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string stream_url = 1;
          if (!this_._internal_stream_url().empty()) {
            const std::string& _s = this_._internal_stream_url();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "marsrover.CameraStreamResponse.stream_url");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:marsrover.CameraStreamResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CameraStreamResponse::ByteSizeLong(const MessageLite& base) {
          const CameraStreamResponse& this_ = static_cast<const CameraStreamResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CameraStreamResponse::ByteSizeLong() const {
          const CameraStreamResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:marsrover.CameraStreamResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string stream_url = 1;
            if (!this_._internal_stream_url().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_stream_url());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CameraStreamResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CameraStreamResponse*>(&to_msg);
  auto& from = static_cast<const CameraStreamResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:marsrover.CameraStreamResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_stream_url().empty()) {
    _this->_internal_set_stream_url(from._internal_stream_url());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CameraStreamResponse::CopyFrom(const CameraStreamResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:marsrover.CameraStreamResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CameraStreamResponse::InternalSwap(CameraStreamResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.stream_url_, &other->_impl_.stream_url_, arena);
}

::google::protobuf::Metadata CameraStreamResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace marsrover
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mars_5frover_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
